language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install --use-mirrors importlib unittest2; fi
  - pip install flake8 python-coveralls
  - pip install -e .
  - pip install "file://`pwd`#egg=content-io[tests]"

script:
  - make flake8
  - coverage run --source cio runtests.py
  - coverage report

after_success:
  - coveralls
