language: python

python:
  - "2.6"
  - "2.7"

install:
  - pip install flake8 python-coveralls
  - pip install -e .
  - pip install "file://`pwd`#egg=content-io[tests]"

script:
  - make flake8
  - coverage run --source cio runtests.py
  - coverage report

after_success:
  - coveralls
